// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "TPCdesign_types.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// logit
NumericVector logit(NumericVector p);
RcppExport SEXP _TPCdesign_logit(SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(logit(p));
    return rcpp_result_gen;
END_RCPP
}
// inv_logit
NumericVector inv_logit(NumericVector a);
RcppExport SEXP _TPCdesign_inv_logit(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(inv_logit(a));
    return rcpp_result_gen;
END_RCPP
}
// trunc_rnorm
arma::vec trunc_rnorm(const uint32& n, const double& mu, const double& sigma);
RcppExport SEXP _TPCdesign_trunc_rnorm(SEXP nSEXP, SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const uint32& >::type n(nSEXP);
    Rcpp::traits::input_parameter< const double& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const double& >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(trunc_rnorm(n, mu, sigma));
    return rcpp_result_gen;
END_RCPP
}
// trunc_rnorm_range
arma::vec trunc_rnorm_range(const uint32& n, const double& mu, const double& sigma);
RcppExport SEXP _TPCdesign_trunc_rnorm_range(SEXP nSEXP, SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const uint32& >::type n(nSEXP);
    Rcpp::traits::input_parameter< const double& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const double& >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(trunc_rnorm_range(n, mu, sigma));
    return rcpp_result_gen;
END_RCPP
}
// briere2_tpc
arma::vec briere2_tpc(const arma::vec& temp, const double& ctmin, const double& ctmax, const double& a, const double& b, const bool& scale);
RcppExport SEXP _TPCdesign_briere2_tpc(SEXP tempSEXP, SEXP ctminSEXP, SEXP ctmaxSEXP, SEXP aSEXP, SEXP bSEXP, SEXP scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type temp(tempSEXP);
    Rcpp::traits::input_parameter< const double& >::type ctmin(ctminSEXP);
    Rcpp::traits::input_parameter< const double& >::type ctmax(ctmaxSEXP);
    Rcpp::traits::input_parameter< const double& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const double& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const bool& >::type scale(scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(briere2_tpc(temp, ctmin, ctmax, a, b, scale));
    return rcpp_result_gen;
END_RCPP
}
// briere2_tpc_deriv
arma::vec briere2_tpc_deriv(const arma::vec& temp, const double& ctmin, const double& ctmax, const double& a, const double& b);
RcppExport SEXP _TPCdesign_briere2_tpc_deriv(SEXP tempSEXP, SEXP ctminSEXP, SEXP ctmaxSEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type temp(tempSEXP);
    Rcpp::traits::input_parameter< const double& >::type ctmin(ctminSEXP);
    Rcpp::traits::input_parameter< const double& >::type ctmax(ctmaxSEXP);
    Rcpp::traits::input_parameter< const double& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const double& >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(briere2_tpc_deriv(temp, ctmin, ctmax, a, b));
    return rcpp_result_gen;
END_RCPP
}
// make_temps
NumericVector make_temps(NumericVector params, const double& temp_min, const double& temp_max);
RcppExport SEXP _TPCdesign_make_temps(SEXP paramsSEXP, SEXP temp_minSEXP, SEXP temp_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< const double& >::type temp_min(temp_minSEXP);
    Rcpp::traits::input_parameter< const double& >::type temp_max(temp_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(make_temps(params, temp_min, temp_max));
    return rcpp_result_gen;
END_RCPP
}
// rmse_objective
double rmse_objective(const arma::vec& params, const arma::vec& y, const arma::vec& temp, const bool& scale_tpc);
RcppExport SEXP _TPCdesign_rmse_objective(SEXP paramsSEXP, SEXP ySEXP, SEXP tempSEXP, SEXP scale_tpcSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type temp(tempSEXP);
    Rcpp::traits::input_parameter< const bool& >::type scale_tpc(scale_tpcSEXP);
    rcpp_result_gen = Rcpp::wrap(rmse_objective(params, y, temp, scale_tpc));
    return rcpp_result_gen;
END_RCPP
}
// sim_gamma_data
DataFrame sim_gamma_data(const arma::vec& temp, const int& n_reps, const double& obs_cv, const double& ctmin, const double& ctmax, const double& a, const double& b, const bool& scale_tpc);
RcppExport SEXP _TPCdesign_sim_gamma_data(SEXP tempSEXP, SEXP n_repsSEXP, SEXP obs_cvSEXP, SEXP ctminSEXP, SEXP ctmaxSEXP, SEXP aSEXP, SEXP bSEXP, SEXP scale_tpcSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type temp(tempSEXP);
    Rcpp::traits::input_parameter< const int& >::type n_reps(n_repsSEXP);
    Rcpp::traits::input_parameter< const double& >::type obs_cv(obs_cvSEXP);
    Rcpp::traits::input_parameter< const double& >::type ctmin(ctminSEXP);
    Rcpp::traits::input_parameter< const double& >::type ctmax(ctmaxSEXP);
    Rcpp::traits::input_parameter< const double& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const double& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const bool& >::type scale_tpc(scale_tpcSEXP);
    rcpp_result_gen = Rcpp::wrap(sim_gamma_data(temp, n_reps, obs_cv, ctmin, ctmax, a, b, scale_tpc));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_TPCdesign_logit", (DL_FUNC) &_TPCdesign_logit, 1},
    {"_TPCdesign_inv_logit", (DL_FUNC) &_TPCdesign_inv_logit, 1},
    {"_TPCdesign_trunc_rnorm", (DL_FUNC) &_TPCdesign_trunc_rnorm, 3},
    {"_TPCdesign_trunc_rnorm_range", (DL_FUNC) &_TPCdesign_trunc_rnorm_range, 3},
    {"_TPCdesign_briere2_tpc", (DL_FUNC) &_TPCdesign_briere2_tpc, 6},
    {"_TPCdesign_briere2_tpc_deriv", (DL_FUNC) &_TPCdesign_briere2_tpc_deriv, 5},
    {"_TPCdesign_make_temps", (DL_FUNC) &_TPCdesign_make_temps, 3},
    {"_TPCdesign_rmse_objective", (DL_FUNC) &_TPCdesign_rmse_objective, 4},
    {"_TPCdesign_sim_gamma_data", (DL_FUNC) &_TPCdesign_sim_gamma_data, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_TPCdesign(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
