// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "TPCdesign_types.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// logit
NumericVector logit(NumericVector p);
RcppExport SEXP _TPCdesign_logit(SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(logit(p));
    return rcpp_result_gen;
END_RCPP
}
// inv_logit
NumericVector inv_logit(NumericVector a);
RcppExport SEXP _TPCdesign_inv_logit(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(inv_logit(a));
    return rcpp_result_gen;
END_RCPP
}
// briere2_tpc
NumericVector briere2_tpc(NumericVector temp, const double& CTmin, const double& CTmax, const double& a, const double& b, const bool& scale);
RcppExport SEXP _TPCdesign_briere2_tpc(SEXP tempSEXP, SEXP CTminSEXP, SEXP CTmaxSEXP, SEXP aSEXP, SEXP bSEXP, SEXP scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type temp(tempSEXP);
    Rcpp::traits::input_parameter< const double& >::type CTmin(CTminSEXP);
    Rcpp::traits::input_parameter< const double& >::type CTmax(CTmaxSEXP);
    Rcpp::traits::input_parameter< const double& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const double& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const bool& >::type scale(scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(briere2_tpc(temp, CTmin, CTmax, a, b, scale));
    return rcpp_result_gen;
END_RCPP
}
// make_temps
NumericVector make_temps(NumericVector params, const double& temp_min, const double& temp_max, const int& n_temps);
RcppExport SEXP _TPCdesign_make_temps(SEXP paramsSEXP, SEXP temp_minSEXP, SEXP temp_maxSEXP, SEXP n_tempsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< const double& >::type temp_min(temp_minSEXP);
    Rcpp::traits::input_parameter< const double& >::type temp_max(temp_maxSEXP);
    Rcpp::traits::input_parameter< const int& >::type n_temps(n_tempsSEXP);
    rcpp_result_gen = Rcpp::wrap(make_temps(params, temp_min, temp_max, n_temps));
    return rcpp_result_gen;
END_RCPP
}
// make_temps2
NumericVector make_temps2(NumericVector params, const double& temp_min, const double& temp_max);
RcppExport SEXP _TPCdesign_make_temps2(SEXP paramsSEXP, SEXP temp_minSEXP, SEXP temp_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< const double& >::type temp_min(temp_minSEXP);
    Rcpp::traits::input_parameter< const double& >::type temp_max(temp_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(make_temps2(params, temp_min, temp_max));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_TPCdesign_logit", (DL_FUNC) &_TPCdesign_logit, 1},
    {"_TPCdesign_inv_logit", (DL_FUNC) &_TPCdesign_inv_logit, 1},
    {"_TPCdesign_briere2_tpc", (DL_FUNC) &_TPCdesign_briere2_tpc, 6},
    {"_TPCdesign_make_temps", (DL_FUNC) &_TPCdesign_make_temps, 4},
    {"_TPCdesign_make_temps2", (DL_FUNC) &_TPCdesign_make_temps2, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_TPCdesign(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
