# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

utility_briere2D <- function(d, B) {
    .Call(`_TPCdesign_utility_briere2D`, d, B)
}

#' Logit and inverse logit functions.
#'
#'@param p Numeric vector of proportion(s)
#' @export
#'
logit <- function(p) {
    .Call(`_TPCdesign_logit`, p)
}

#' @rdname logit
#'
#'@param a Numeric vector of values that aren't necessarily proportions
#'
#' @export
#'
inv_logit <- function(a) {
    .Call(`_TPCdesign_inv_logit`, a)
}

trunc_rnorm <- function(n, mu, sigma) {
    .Call(`_TPCdesign_trunc_rnorm`, n, mu, sigma)
}

trunc_rnorm_range <- function(n, mu, sigma) {
    .Call(`_TPCdesign_trunc_rnorm_range`, n, mu, sigma)
}

#' Brière-2 thermal performance curve (TPC)
#'
#' Note that this TPC does not perform well when ctmin is positive, but
#' there are negative temperatures.
#' For example, if you run `briere2_tpc(c(-10, 0, 10), ctmin = 5,
#' ctmax = 30, a = 1, b = 0.2, TRUE)`, you'll see that a temperature of `-10`
#' gives a greater performance value than `10`.
#'
#' @param temp Numeric vector of temperatures
#' @param ctmin Single numeric for parameter `ctmin`.
#' @param ctmax Single numeric for parameter `ctmax`.
#' @param a Single numeric for parameter `a`.
#' @param b Single numeric for parameter `b`.
#' @param scale Single logical for whether to scale to make max value 1.
#'     Defaults to `FALSE`.
#'
#' @returns A numeric vector for measure of performance for each in `temp`
#'
#' @export
#'
briere2_tpc <- function(temp, ctmin, ctmax, a, b, scale = FALSE) {
    .Call(`_TPCdesign_briere2_tpc`, temp, ctmin, ctmax, a, b, scale)
}

#' Derivative of Brière-2 thermal performance curve (TPC) with respect to time
#'
#'
#' @inheritParams briere2_tpc
#'
#' @returns A numeric vector for first derivative of measures of
#' performance for each in `temp`
#'
#' @export
#'
briere2_tpc_deriv <- function(temp, ctmin, ctmax, a, b) {
    .Call(`_TPCdesign_briere2_tpc_deriv`, temp, ctmin, ctmax, a, b)
}

#' Simulate data with gamma distributed error (or normal approximation)
#'
#' @param temp Numeric vector giving the observed temperatures for each
#'     performance value.
#' @param n_reps Single integer for the number of experimental reps per
#'     temperature.
#' @param obs_cv Single numeric for the observation error coefficient of variation.
#'     Must be >= 0.
#'     Observation error is simulated using a gamma distribution, except for
#'     when performance values would fall below zero, in which case it uses
#'     a truncated normal approximation.
#' @inheritParams briere2_tpc
#' @param scale_tpc Single logical for whether to scale to make max value 1.
#'     Defaults to `FALSE`.
#'
#' @export
#'
#' @returns A dataframe of temperatures (column `"temp"`) and
#'     performance values (column `"y"`) with gamma (or normal approximation)
#'     error.
#'
sim_gamma_data <- function(temp, n_reps, obs_cv, ctmin, ctmax, a, b, scale_tpc = FALSE) {
    .Call(`_TPCdesign_sim_gamma_data`, temp, n_reps, obs_cv, ctmin, ctmax, a, b, scale_tpc)
}

