# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Logit and inverse logit functions.
#'
#'
#' @export
#'
logit <- function(p) {
    .Call(`_TPCdesign_logit`, p)
}

#' @describeIn logit
#'
#' @export
#'
inv_logit <- function(a) {
    .Call(`_TPCdesign_inv_logit`, a)
}

#' Brière-2 thermal performance curve (TPC)
#'
#' Note that this TPC does not perform well when ctmin is positive, but
#' there are negative temperatures.
#' For example, if you run `briere2_tpc(c(-10, 0, 10), ctmin = 5,
#' ctmax = 30, a = 1, b = 0.2, TRUE)`, you'll see that a temperature of `-10`
#' gives a greater performance value than `10`.
#'
#' @param temp Numeric vector of temperatures
#' @param ctmin Single numeric for parameter ctmin
#' @param ctmax Single numeric for parameter ctmax
#' @param a Single numeric for parameter a
#' @param b Single numeric for parameter b
#' @param scale Single logical for whether to scale to make max value 1.
#'
#' @returns A numeric vector for measure of performance for each in `temp`
#'
#' @export
#'
briere2_tpc <- function(temp, ctmin, ctmax, a, b, scale) {
    .Call(`_TPCdesign_briere2_tpc`, temp, ctmin, ctmax, a, b, scale)
}

#' Make vector of temperatures for input of parameters
#'
#' @param params Numeric vector of parameters.
#'     The length of this vector must be equal to the number of desired
#'     temperatures plus 1. A vector of length `<2` returns an error.
#'     The last item in this vector must be the logit-transformed proportion
#'     the last temperature is from the midpoint
#'     (i.e., `mean(c(temp_min, temp_max))`)
#'     to the maximum possible temperature (i.e., `temp_max`).
#'     The first item is the logit-transformed weight affecting
#'     the difference between `temp_min` and the first sampled temperature.
#'     The remaining items are the logit-transformed weights affecting
#'     the distance between the remaining sampled temperatures and
#'     the previous ones.
#' @inheritParams design_temps
#'
#' @returns A numeric vector for the temperatures to sample.
#'
#' @export
#'
#'
make_temps <- function(params, temp_min, temp_max) {
    .Call(`_TPCdesign_make_temps`, params, temp_min, temp_max)
}

#' Objective function with RMSE returned
#'
#' @param params Numeric vector of length 4 containing (in order)
#'     untransformed `ctmin`, untransformed `ctmax`, log-transformed `a`,
#'     and log-transformed `b`.
#' @param y Numeric vector giving the observed performance values for each
#'     temperature. It's recommended to scale this vector to have a max value
#'     of 1 by dividing by its max value.
#'     Must be the same length as `temp`.
#' @param temp Numeric vector giving the observed temperatures for each
#'     performance value. Must be the same length as `y`.
#' @param scale_tpc Single logical for whether to scale TPC to make max value 1.
#'
#' @returns A single numeric giving the RMSE between observed performance
#'     values and those predicted based on the input parameters.
#'
#' @noRd
#'
#'
rmse_objective <- function(params, y, temp, scale_tpc) {
    .Call(`_TPCdesign_rmse_objective`, params, y, temp, scale_tpc)
}

#' Simulate data with gamma distributed error (or normal approximation)
#'
#' @param temp Numeric vector giving the observed temperatures for each
#'     performance value.
#' @inheritParams design_temps
#'
#' @export
#'
#' @returns A dataframe of temperatures (column `"temp"`) and
#'     performance values (column `"y"`) with gamma (or normal approximation)
#'     error.
#'
sim_gamma_data <- function(temp, n_reps, obs_cv, ctmin, ctmax, a, b, scale_tpc = TRUE) {
    .Call(`_TPCdesign_sim_gamma_data`, temp, n_reps, obs_cv, ctmin, ctmax, a, b, scale_tpc)
}

