# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Logit and inverse logit functions.
#'
#'
#' @export
#'
logit <- function(p) {
    .Call(`_TPCdesign_logit`, p)
}

#' @describeIn logit
#'
#' @export
#'
inv_logit <- function(a) {
    .Call(`_TPCdesign_inv_logit`, a)
}

#' Brière-2 thermal performance curve (TPC)
#'
#' @param temp Numeric vector of temperatures
#' @param CTmin Single numeric for parameter CTmin
#' @param CTmax Single numeric for parameter CTmax
#' @param a Single numeric for parameter a
#' @param b Single numeric for parameter b
#' @param scale Single logical for whether to scale to make max value 1.
#'     Defaults to `TRUE`
#'
#' @returns A numeric vector for measure of performance for each in `temp`
#'
#' @export
#'
briere2_tpc <- function(temp, CTmin, CTmax, a, b, scale = TRUE) {
    .Call(`_TPCdesign_briere2_tpc`, temp, CTmin, CTmax, a, b, scale)
}

#' Make vector of temperatures for input of parameters
#'
#' @param temp Numeric vector of parameters. The first must be the
#'     logit-transformed proportion the first temperature to be sampled is
#'     from `temp_min` to `(temp_min + temp_max) / 2`.
#'     The second is the same for the proportion the last temperature to
#'     be sampled is from the midpoint to `temp_max`.
#'     The third and fourth (if present) are the `log(shape1)` and
#'     `log(shape2)`, respectively, for a beta distribution.
#'     This distribution is used to generate quantiles to make the temperatures
#'     not evenly distributed through the temperature space.
#' @param temp_min Single numeric for the minimum possible temperature allowed.
#' @param temp_max Single numeric for the maximum possible temperature allowed.
#' @param n_temps Single integer for the number of temperatures to sample.
#'
#' @returns A numeric vector for the temperatures to sample.
#'
#'
make_temps <- function(params, temp_min, temp_max, n_temps) {
    .Call(`_TPCdesign_make_temps`, params, temp_min, temp_max, n_temps)
}

make_temps2 <- function(params, temp_min, temp_max) {
    .Call(`_TPCdesign_make_temps2`, params, temp_min, temp_max)
}

